# Generated by Django 5.2 on 2025-04-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('adress', models.CharField(max_length=25, verbose_name='adress')),
                ('phone_number', models.IntegerField(verbose_name='phone_number')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('website', models.CharField(max_length=25, verbose_name='site')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
            },
        ),
    ]
